### PR TITLE
Make CI green

### PR DESCRIPTION
**Pull request by VictorBjelkholm**

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Not passing on AppVeyor with:

```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

Not passing on TravisCI with:

```
GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109
```

Passing on CircleCI and Jenkins though 👍

**Comment by diasdavid** [comment]
@VictorBjelkholm while you are doing this, could you also update the Travis and Circle CI files (see js-ipfs and js-ipfs-api for the latest) and add AppVeyor configs?

**Comment by VictorBjelkholm** [comment]
@diasdavid on it at this very moment :)

**Comment by VictorBjelkholm** [comment]
@diasdavid all green and ready to be merged!

**Comment by diasdavid** [comment]
Love it!

**Pull request merged**
